on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir build
      - run: zip -r build/Essentials.love .
      - uses: actions/upload-artifact@v3
        with:
          name: Essentials
          path: build
